// Configuration for this identification dataset
window.HEADER_DATA = Object.freeze({
  "SHORT_TITLE": "Lucilia — USA & Canada",
  "LONG_TITLE": "Interactive field-character key to <i>Lucilia</i> of the USA and Canada",
  "DEFAULT_PLACE_ID": "6712,1",
  "DEFAULT_TAXON": "61858",
  "ABOUT_CONTENT": "This interactive key to <i>Lucilia</i> was created by Even Dankowicz.\n<p>Most of the features used in this key are explained in my <a href=\"lucilia_us_canada.pdf\">illustrated guide to Greenbottle Flies (Calliphoridae: <i>Lucilia</i>) of the USA and Canada</a>. Many features are also shown in <a href=\"https://cjai.biologicalsurvey.ca/wp-content/uploads/2021/01/jwm_39.pdf\">Jones et al (2019)</a>, which is the best resource to start identifying specimens under a microscope. For my other fly ID resources, visit <a href=\"https://sites.google.com/view/flyguide/\">https://sites.google.com/view/flyguide/</a>.\n\t<br><br>\n\t<p>I refined this dataset by studying preserved specimens, live flies, and photos.\n\tA lot of the trait and distribution records were initially derived from the following references:\n\t<p>\n\tFalk, 2016. British Blowflies (Calliphoridae) and Woodlouse Flies (Rhinophoridae). Draft Key March 2016. https://quelestcetanimal-lagalerie.com/wp-content/uploads/2017/01/testkeytobritishblowflies132016.pdf \n\t<p>Hall, Townsend, 1977. The Blow Flies of Virginia (Diptera: Calliphoridae). Virginia Tech Research Division Bulletin 123.\n\t<p>Jones, Whitworth, Marshall, 2019. Blow flies of North America: Keys to the subfamilies and genera of Calliphoridae, and to the species of the subfamilies Calliphorinae, Luciliinae and Chrysomyinae. Canadian Journal of Arthropod Identification. 39. https://cjai.biologicalsurvey.ca/jwm_39/jwm_39.html \n\t<p>Marshall, Whitworth, Roscoe, 2011. Blow flies (Diptera: Calliphoridae) of eastern Canada with a key to Calliphoridae subfamilies and genera of eastern North America, and a key to the eastern Canadian species of Calliphorinae, Luciliinae and Chrysomyiinae. Canadian Journal of Arthropod Identification. 11.\n\t<p>Tantawi, Whitworth, 2014. First record of Lucilia bufonivora Moniez, 1876 (Diptera: Calliphoridae) from North America and key to North American species of the L. bufonivora species group. Zootaxa. 3881(2): 101-124\n\t<p>Whitworth, 2006. Keys to the Genera and Species of Blow Flies (Diptera: Calliphoridae) of North America north of Mexico. Proceedings of the Entomological Society of Washington. 108(3): 689-725.\n\t<p>Whitworth, 2010. Keys to the genera and species of blow flies (Diptera: Calliphoridae) of the WestIndies and description of a new species of Lucilia Robineau-Desvoidy. Zootaxa.\n\t<p>Whitworth, 2014. A revision of the Neotropical species of Lucilia Robineau-Desvoidy (Diptera: Calliphoridae). Zootaxa.\t<p>Williams, Villet, 2014. Morphological identification of Lucilia sericata, Lucilia cuprina and their hybrids (Diptera, Calliphoridae). ZooKeys 420. https://zookeys.pensoft.net/article/3908/\n    </p>\n\n"
});

window.SHORT_TITLE = window.HEADER_DATA.SHORT_TITLE;
window.LONG_TITLE = window.HEADER_DATA.LONG_TITLE;
window.DEFAULT_PLACE_ID = window.HEADER_DATA.DEFAULT_PLACE_ID;
window.DEFAULT_TAXON = window.HEADER_DATA.DEFAULT_TAXON;
window.ABOUT_CONTENT = window.HEADER_DATA.ABOUT_CONTENT;
